// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/errordeveloper/kue/cmd/crdgen/types

package types

Cluster :: {
	metadata: ClusterMeta @go(Metadata)
	spec:     ClusterSpec @go(Spec)
}

ClusterMeta :: {
	namespace: string @go(Namespace)
	name:      string @go(Name)
}

ClusterSpec :: {
	location: string @go(Location)
}
